# Generated by Django 3.0 on 2022-05-09 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_id', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('engineer', 'engineer'), ('HR', 'HR')], max_length=50)),
                ('need_to_accept', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=20, null=True)),
                ('wording', models.TextField()),
                ('policy_id', models.CharField(max_length=20)),
                ('applicable_to', models.CharField(max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcceptedPolicies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=20, null=True)),
                ('is_periodic', models.BooleanField(default=True)),
                ('fk_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logics.Employee', verbose_name='employee')),
                ('fk_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logics.Policies', verbose_name='policy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
